"""empty message

Revision ID: 172842af2f58
Revises: 476faaa90677
Create Date: 2021-12-25 11:37:40.919639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172842af2f58'
down_revision = '476faaa90677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
