"""empty message

Revision ID: 5abf953c9d8b
Revises: 172842af2f58
Create Date: 2021-12-25 11:43:30.246649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abf953c9d8b'
down_revision = '172842af2f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
