"""empty message

Revision ID: cea10c4cc514
Revises: 5abf953c9d8b
Create Date: 2021-12-25 11:46:42.473109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea10c4cc514'
down_revision = '5abf953c9d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
